import type { Metadata } from "next";
import { Nunito_Sans, Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin']
})

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
